config:
  request:
    iplimit:
      apis: /api/user/register/
      intervalMinutes: 1
      maxRequestCount: 5
  response:
    message:
      seeother: 频繁注册，请求已被拒绝！
      unauthorize: 您的请求未经授权，请登录或注册后再访问！
  code:
    validate:
      #expire: 600
      expire: 20
  email:
    host: smtp.163.com
    sender:
      name: 
      password: 
    templates:
      checkcode:
        title: 注册验证码
        content: 您好，本次登录的验证码为：%s，将在10分钟之后过期

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: 
    password: 
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://SpringCloudEurekaServerA:8761/eureka,http://SpringCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        exlude: "*"
